config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
get 'dashboard' => 'pages#dashboard'

  resources :vehicles do
    resources :reviews
    resources :reservations
  end

  root to: 'pages#home'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :vehicles
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :vehicle
  belongs_to :user
  validates :user, presence: true
  validates :vehicle, presence: true
  # validates :start_date, presence: true
  # validates :end_date, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :vehicle
  belongs_to :user
  validates :rating, inclusion: { in: [0,1,2,3,4,5], allow_nil: false },numericality: {only_integer: true}
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :omniauthable, omniauth_providers: [:facebook]
  validates :first_name, presence: true
  validates :last_name, presence: true
  mount_uploader :avatar, PhotoUploader
  after_create :send_welcome_email

  has_many :reservations


  def self.find_for_facebook_oauth(auth)
   user_params = auth.to_h.slice(:provider, :uid)
   user_params.merge! auth.info.slice(:email, :first_name, :last_name)
   user_params[:facebook_picture_url] = auth.info.image
   user_params[:token] = auth.credentials.token
   user_params[:token_expiry] = Time.at(auth.credentials.expires_at)

   user = User.where(provider: auth.provider, uid: auth.uid).first
   user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
   if user
     user.update(user_params)
   else
     user = User.new(user_params)
     user.password = Devise.friendly_token[0,20]  # Fake password for validation
     user.save
   end

   return user
  end



  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end
 end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  geocoded_by :city
  after_validation :geocode#, if: :city_changed?
  has_many :reservations, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :user
  belongs_to :category
  validates :user, presence: true
  validates :description, presence: true
  validates :marque, presence: true
  validates :category, presence: true
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!


  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :email, :avatar, :avatar_cache])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:phone_number, :email, :avatar, :avatar_cache])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @vehicle = Vehicle.new
    @categories = Category.all
    @reviews = Review.all
    @vehicle_one = Vehicle.all.sample
    @vehicle_two = Vehicle.all.sample
    @vehicle_three = Vehicle.all.sample
  end

  def dashboard
    @selfreserv = []
    Reservation.all.each do |res|
      @selfreserv << res  if res.vehicle.user == current_user
    end
    
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  before_action :set_vehicle

  def index
    @reservations = @vehicle.reservations
  end

  def show
  end

  def new
    @reservation = Reservation.new
  end

  def create

    @reservation = @vehicle.reservations.new(reservation_params)
    if @reservation.save
      redirect_to @vehicle
    else
      render @vehicle
    end
  end

  def edit
  end

  def update
    @vehicle.update
  end

  def destroy
    @reservation.destroy
    redirect_to @vehicle
  end

  private

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  def reservation_params
    params.require(:reservation).permit(:user, :vehicle, :available, :start_date, :end_date)
  end

  def set_vehicle
    @vehicle = Vehicle.find(params[:vehicle_id])
  end

  def range_params
    start_year = reservation_params["start_date(1i)"].to_i
    start_month = reservation_params["start_date(2i)"].to_i
    start_day = reservation_params["start_date(3i)"].to_i
    end_year = reservation_params["end_date(1i)"].to_i
    end_month = reservation_params["end_date(2i)"].to_i
    end_day = reservation_params["end_date(3i)"].to_i
    st_date = Date.new(start_year,start_month,start_day).to_i
    en_date = Date.new(end_year,end_month,end_day).to_i

    range_date = [st_date..en_date]
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_vehicle, only: [ :new, :create ]

  def new
    @review = @vehicle.reviews.new
  end

  def create
    @review = @vehicle.reviews.build(review_params)
    @review.user = current_user
    if @review.save
    redirect_to vehicle_path(@vehicle.id)
    else
      @reservation = Reservation.new
      render '/vehicles/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
  def find_vehicle
    @vehicle = Vehicle.find(params[:vehicle_id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @vehicles = params_search[:city].blank? ? Vehicle.all : Vehicle.near(params_search[:city], 10)
    @vehicles = params_search[:category].to_i == 0 ? @vehicles : @vehicles.where(category: Category.find(params_search[:category].to_i))

    @hash = Gmaps4rails.build_markers(@vehicles) do |flat, marker|
      marker.lat flat.latitude
      marker.lng flat.longitude
    end
  end

  def show
    @reservations = @vehicle.reservations
    @reservation = @vehicle.reservations.new
    @review = @vehicle.reviews.new
    @reviews = Review.where(vehicle_id: @vehicle.id)
    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  def new
    @vehicle = Vehicle.new
    @categories = Category.all
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    Cloudinary::Uploader.upload(vehicle_params[:photo])
    if @vehicle.save
      redirect_to @vehicle
    else
      render :new
    end
  end

  def edit
  end

  def update
    @vehicle.update(param)
    redirect_to vehicle_path(@vehicle)
  end

  def destroy
    if @vehicle.user == current_user
    @vehicle.destroy
  end
    redirect_to request.referer
  end

  private

  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  def param
    params.require(:vehicle).permit(:user, :description, :marque, :category, :city, :photo, :photo_cache)
  end

  def vehicle_params
    {marque: param[:marque],
     description: param[:description],
     user: current_user, city: param[:city],
     category: Category.find(param[:category].to_i),
     photo: param[:photo]}
   end

   def params_search
    params[:search]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/views/layouts/_alert.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_footer.html.erb
<div id="footer">
  <ul class="list-inline">
    <li><a href=""><i class="fa fa-youtube"></i></a></li>
    <li><a href=""><i class="fa fa-instagram"></i></a></li>
    <li><a href=""><i class="fa fa-facebook"></i></a></li>
    <li><a href=""><i class="fa fa-twitter"></i></a></li>
  </ul>
  <p>This is a FullCar @ LeWagon</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>TODO</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
</head>
<body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <% if devise_controller? %>
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <%= yield %>
      </div>
    </div>
  </div>
  <% else %>
  <%= yield %>
  <% end %>
  <%= render 'layouts/footer' %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
<%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=AIzaSyCSyPNACNGff0Vb-SvpO9N1jrfAWR4oAeg" %>
  <%= javascript_include_tag 'application' %>

  <%= yield(:after_js) %>
</body>
</html>

app/views/pages/_card.html.erb
<div class="col-xs-12 col-sm-4">
  <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= vehicle.photo %>');">
  <div class="card-category"><%= vehicle.user.first_name%></div>

    <div class="card-description">
      <h2><%= vehicle.marque %> </h2>
      <p><%= vehicle.description[0..50] %></p>
    </div>
    <%= image_tag vehicle.user.avatar, class:"card-user avatar-large" %>
    <%= link_to '', vehicle, class: "card-link" %>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="text-center">
<h1><%= image_tag current_user.avatar, class: "avatar-large" %><%= "#{current_user.first_name} #{current_user.last_name}" %></h1>
</div>

<div id="dashboard">
  <div class="text-center">
    <h1 class="count"><%= current_user.reservations.count %></h1>
  </div>
</div>
<div class="text-center">
  <h1>Reservations</h1>
</div>
<div class="container">
  <div class="row">
    <% current_user.reservations.each do |reservation| %>
    <div class="col-xs-12 col-md-4 card_marge">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= reservation.vehicle.photo %>');">
        <div class="card-category"><%= reservation.vehicle.user.first_name%> <%= reservation.vehicle.user.last_name %></div>
        <div class="card-description">
        <h2><%= reservation.vehicle.marque %> </h2>
        <p><%= reservation.start_date %> -- <%= reservation.end_date %></p>
        <div class="star-rating" data-score="<%= reservation.rating %>" ></div>
        <p><%= reservation.vehicle.description[0..50] %></p>
        </div>
        <%= image_tag reservation.vehicle.user.avatar, class:"card-user avatar-large" %>
        <%= link_to '', reservation.vehicle, class: "card-link" %>
        </div>

        </div>
        <% end%>
    </div>
  </div>

  <div class="text-center">
    <h1>Reservations of your vehicles</h1>
  </div>
  <div class="container">
    <div class="row">
      <% current_user.reservations.first(5).each do |reservation| %>
      <div class="col-xs-12 col-md-4 card_marge">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= Vehicle.first.photo %>');">
          <div class="card-category"><%= reservation.user.first_name%> <%= reservation.user.last_name %></div>
          <div class="card-description">
          <h2><%= Vehicle.first.marque %> </h2>
          <p><%= reservation.start_date %> -- <%= reservation.end_date %></p>
          <p><div class="star-rating" data-score="<%= reservation.rating %>" ></div></p>
          <p><%= reservation.vehicle.description[0..50] %></p>
          </div>
          <%= image_tag current_user.avatar, class:"card-user avatar-large" %>
          <%= link_to '', Vehicle.first, class: "card-link" %>
          </div>

          </div>
          <% end%>
      </div>
    </div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path 'A.jpg' %>');">
  <div class="banner-content">
    <h1>Welcome Home</h1>
    <p>Select the vehicle you want to rent</p>

    <%= simple_form_for :search, url: vehicles_path, method: :get, html: {class: "form-inline"} do |f| %>
      <%= f.input :city, placeholder: 'City ?', label: false,input_html: {class: "form-control input-lg"} %>
      <%= f.input :date, as: :date, label: false,input_html: {class: "form-control input-lg"} %>
      <%= f.input :category, label: false,prompt: "Select category", collection: @categories, input_html: {class: "form-control input-lg"}%>

      <p class="home_button"><%= f.button :submit, input_html: {class: "btn btn-primary btn-lg"}%></p>
    <% end %>

  </div>
</div>

<div class="text-center padded features">
  <div class="container">
    <div class="row">
      <h1 class="text-center">Enjoy your ride</h1>
      <p>Be unique and rent the trendiest vehicle</p>
      <br>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <i class="fa fa-car fa-3x" aria-hidden="true"></i>
        <h2>Cars</h2>
        <p>The earth is your new home.</p>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <i class="fa fa-ship fa-3x" aria-hidden="true"></i>
        <h2>Boat</h2>
        <p>No cash issues anymore.</p>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <i class="fa fa-motorcycle fa-3x" aria-hidden="true"></i>
        <h2>Motorbike</h2>
        <p>Discover new culture and lifestyle.</p>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3 ">
        <i class="fa fa-bus fa-3x" aria-hidden="true"></i>
        <h2>Van</h2>
        <p>Join a community you will love.</p>
      </div>
    </div>
  </div>
</div>

<div class="wrapper-grey padded">
  <div class="container">
    <div class="row">
      <h1 class='text-center'>Discover the Mov'bnb selection </h1>
      <hr>

      <%= render 'card', vehicle: @vehicle_one %>
      <%= render 'card', vehicle: @vehicle_two %>
      <%= render 'card', vehicle: @vehicle_three %>

    </div>
  </div>
</div>

app/views/reservation/_form.html.erb
<%= simple_form_for [@vehicle,@reservation] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/reservation/create.html.erb
<h1>Reservation#create</h1>
<p>Find me in app/views/reservation/create.html.erb</p>

app/views/reservation/destroy.html.erb
<h1>Reservation#destroy</h1>
<p>Find me in app/views/reservation/destroy.html.erb</p>

app/views/reservation/edit.html.erb
<h1>Reservation#edit</h1>
<p>Find me in app/views/reservation/edit.html.erb</p>

app/views/reservation/index.html.erb
<h1>Reservation#index</h1>
<p>Find me in app/views/reservation/index.html.erb</p>

app/views/reservation/new.html.erb
<h1>Reservation#new</h1>
<p>Find me in app/views/reservation/new.html.erb</p>

app/views/reservation/show.html.erb
<h1>Reservation#show</h1>
<p>Find me in app/views/reservation/show.html.erb</p>

app/views/reservation/update.html.erb
<h1>Reservation#update</h1>
<p>Find me in app/views/reservation/update.html.erb</p>

app/views/reviews/_form.html.erb
<%= simple_form_for [@vehicle, @review] do |f| %>
  <%= f.input :content %>
  <div id="star-rating"></div>
  <br>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/new.html.erb
<%= render 'form' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <h1 class="title_home"><%= image_tag "phenix.png" %> Vehicle's Trip<h1>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>



      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || current_user.avatar %>
          <%= image_tag avatar_url, class: "avatar-large dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Edit Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to dashboard_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Add Vehicle"), new_vehicle_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/vehicles/_form.html.erb
<h1>Add Your vehicles</h1>
<%= simple_form_for(@vehicle) do |f| %>
  <%= f.input :marque %>
  <%= f.input :description %>
  <%= f.input :category , collection: @categories, input_html: {class: "form-control input-lg"} %>
  <%= f.input :city %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit class: "btn btn-danger"%>

<% end %>

app/views/vehicles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="text-center">
<h1><%= @vehicle.marque%></h1>
<p>Change your vehicle if you are note happy
<i class="fa fa-frown-o" aria-hidden="true"></i></p> 
</div>
<%= simple_form_for(@vehicle) do |f| %>
  <%= f.input :marque %>
  <%= f.input :description %>
  <%= f.input :city %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit class: "btn btn-danger"%>

<% end %>
</div>
</div>
</div>

app/views/vehicles/index.html.erb
<div class="listing-content" style="display: flex">
  <div class="listing-cars" style="width: 50%">
  <% @vehicles.each do |vehicle| %>
  <div class="product">
    <div class='product-upvote'>
    </div>
    <%= image_tag vehicle.photo, class: "product-image hidden-xs" %>
    <div class='product-body'>
      <h2><%= link_to vehicle.marque, vehicle, class: "cocktail_name" %></h2>
      <p><%= vehicle.description%></p>
    </div>
    <ul class="list-inline product-controls product-controls-hidden hidden-sm hidden-xs">
    <% if vehicle.user == current_user %>
      <li><%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_vehicle_path(vehicle.id) %></li>
      <li><%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, vehicle_path(vehicle.id),
        method: :delete,
        data: { confirm:"Are you sure?"} %></li>
        <% end %>
        <li><%= link_to '<i class="fa fa-star"></i>'.html_safe, vehicle_path(vehicle.id) %></li>
      </ul>
  </div>
<% end %>

</div>




  <div id="map" style="width: 50%; height: 650px; right: 0px;"></div>

</div>



<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>

app/views/vehicles/new.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path 'girlboat.jpg' %>');">
  <div class="banner-content">
    <h1>Please Add your Vehicles you want to rent</h1>
    <p>Earn money as an Fullcar Owner</p>
    <a  class="btn folder" data-toggle="modal" data-target=".bs-example-modal-lg"><i class="fa fa-folder-o" aria-hidden="true"></i></a>
    <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
      <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">

          <%= render 'form' %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/vehicles/show.html.erb
<div class="media">
  <div class="media-body">

    <div class="media-section">
      <h2><% if @vehicle.category.name == "Car" %>
        <i class="fa fa-car" aria-hidden="true"></i>  <%= @vehicle.marque %>
        <% elsif @vehicle.category.name == "Motorbike" %>
        <i class="fa fa-motorcycle" aria-hidden="true"></i>  <%= @vehicle.marque %>
        <% elsif @vehicle.category.name == "Boat" %>
        <i class="fa fa-ship" aria-hidden="true"></i> <%= @vehicle.marque %>
        <% elsif @vehicle.category.name == "Van" %>
        <i class="fa fa-bus" aria-hidden="true"></i>  <%= @vehicle.marque %>
        <%end%></h2>
        <div class="pitcher-show">
          <%= cl_image_tag @vehicle.photo, class: "photo_show_vehicles img-responsive" %>
        </div>

      </div>

      <div class="media-section">
        <h2>Description</h2>
        <%= @vehicle.description%>
      </div>
    </div>
    <div class="media-aside">

      <div class="media-section">
        <p><%= image_tag @vehicle.user.avatar, class: "avatar-large" %></p>
        <p><i class="fa fa-user" aria-hidden="true"></i>  <%= @vehicle.user.first_name %> <%= @vehicle.user.last_name %></p>
        <p><i class="fa fa-envelope-o" aria-hidden="true"></i>  <%= @vehicle.user.email %></p>
        <p><i class="fa fa-phone" aria-hidden="true"></i>  <%= @vehicle.user.phone_number %></p>
        <p><div class="star-rating" data-score= <%= @avg_review %>></div></p>
      </div>
      <hr>
      <div class="media-section">
        <h2>Reservation</h2>
        <%= render 'reservation/form'%>
        <hr>
        <h2><%= pluralize @vehicle.reviews.count , "Review" %></h2>
        <%= render 'reviews/form' %>
      </div>
      <div class="review_post">
      <% @vehicle.reviews.each do |review| %>
        <% if review.persisted?  %>
        <%= image_tag review.user.avatar, class: "avatar-large" %>  
          <p><%= review.content%></p>
          <div class="star-rating" data-score="<%= review.rating %>" ></div>
          <hr>
        <% end %>
      <% end %>
      </div>
    </div>
  </div>
</div>